### ISSUE TITLE
As a developer, I want to replace VS files with a CMakeLists.txt file

### ISSUE THREAD

**Issue by frtru** [frtru/GemParticles#1]
Currently, I am using an hand-made visual studio solution. My aim is to also develop under a linux distribution, so I'd like to have CMakeLists.txt file that
- Generates the corresponding compilation tools depending on which OS I'm working on
  - A Visual Studio solution when I'm on windows
  - A makefile running gcc or clang when I'm on Linux
- Links with the external libraries I will be using
  - GLM
  - AntTweakBar
  - OpenGL
  - OpenCL
- Includes all the source code in this project

**Comment by frtru** [comment]
Since the last time the Cmake files were updated a lot of new files and external libraries were added to the project. I am currently maintaining a VS solution, but if people want to reuse this project, we need to this for sure.

**Comment by larivierec** [comment]
I'll take a look into this at a later date / time.
I'll use your VS project as a baseline. Have you added new libraries?


Christopher Larivière, B. Ing.
