### ISSUE TITLE
As a developer, I need to integrate SIMD instructions in the particle system

### ISSUE THREAD

**Issue by frtru** [frtru/GemParticles#4]
The system will have a CPU and a GPU version. For the CPU version it would be interesting to test the performance gain when adding SIMD instructions. Depending on where we will draw the line for GPU version maybe I could also add SIMD instructions.

**Comment by frtru** [comment]
This will be added to the current emitters and current dynamics.

**Comment by frtru** [comment]
Apply this also for the repulsors and retractors.

**Comment by frtru** [comment]
http://meseec.ce.rit.edu/756-projects/spring2013/2-2.pdf

**Comment by frtru** [comment]
https://en.wikipedia.org/wiki/X86_assembly_language#Syntax

**Comment by frtru** [comment]
See INF8601 examples in bitbucket.

**Comment by larivierec** [comment]
Usage of assmebly is required?
I thought SIMD instructions were similar to that of "kernels" approach with OpenCL

**Comment by frtru** [comment]
Assembly is not required, but it's faster. SIMD instructions are on the CPU side. They can be used to have less loop iterations  and execute a single instruction over multiple variables. E.g.: __mm_add_ps() executes an addition over a __m128 type (4x packed float variables), instead of doing one addition, incrementing i for next loop, doing it again...you can skip 4,8 or more iterations. Intrinsics are much simpler tho and they are good enough. Moreover, SIMD instructions can be executed in multiple threads to gain optimal performance. If you feel like it you could experiment with assembly, this is really a sandbox to test new techs so feel free to try it out.
