### ISSUE TITLE
Change emitter position with mouse position and left click press

### ISSUE THREAD

**Issue by frtru** [frtru/GemParticles#50]
When pressing left click, particle emitter position should be set accordingly with mouse position translated into world coordinates. Emission rate should also be set to 0 when left button is released.

This implies either changing unique_ptrs for emitters and dynamics in the particle_system to shared_ptrs and add a shared_ptr to the corresponding emitter somewhere (event handler?.....) OR go through an ID for the emitter object ID and add methods in the Iparticle system to set parameters....

**Comment by larivierec** [comment]
I'll look into this. Seems like a good task to start with.
